# Generated by Django 4.2.14 on 2024-07-19 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstname", models.CharField(max_length=30)),
                ("lasstname", models.CharField(max_length=30)),
                ("email", models.EmailField(max_length=30)),
                ("phone", models.CharField(blank=True, max_length=30, null=True)),
                ("job", models.CharField(max_length=30)),
                ("birthday", models.DateField(auto_now_add=True)),
            ],
        ),
    ]
